10_4_2  Anagram 1
AleksandraYanum/Stepik_Python_Advanced pull request #67
Opened 2023-05-25 10:32 UTC by AleksandraYanum

2023-05-25 10:40 UTC, AleksandraYanum commented
@YanumVlad, why should I use dict here?

2023-05-25 20:18 UTC, YanumVlad commented
> @YanumVlad, why should I use dict here?

Performance.
Imagine - both strings are multi-million length like

2023-05-26 15:11 UTC, YanumVlad requested changes

2023-05-26 16:44 UTC, AleksandraYanum commented on 10_dictionary/10_4_dictionary_tasks/2_anagram_1.py
> +    is_anagram = set(word_letter_amount.values()) == {0}
Done

2023-05-29 11:51 UTC, YanumVlad approved these changes

2023-05-29 11:51 UTC, merged